### ISSUE TITLE
Greece (GR)

### ISSUE THREAD

**Issue by octoper** [caneco/laravel-country-logomarks#11]
**Is you request a new country in the list?**
No it's not!

**Your country community links**
**Page**: [laravel.gr](https://www.laravel.gr/)
**Twitter**: [@laravelgr](https://twitter.com/laravelgr)
**Facebook**: [Laravel Greece](https://www.facebook.com/laravelgr)
**Meetup**: [https://www.meetup.com/athens-laravel-meetup](https://www.meetup.com/athens-laravel-meetup)

**Additional context**
**Wikipedia**: [Greek Flag](https://en.wikipedia.org/wiki/Flag_of_Greece)

**Comment by caneco** [comment]
**Here's the preview** 😉

![image](https://user-images.githubusercontent.com/502041/98921974-cfe74a00-24c9-11eb-9b66-578dd38b6384.png)

**Comment by octoper** [comment]
That's awesome @caneco

**Comment by caneco** [comment]
Complete in #16
