### ISSUE TITLE
Indonesia (ID)

### ISSUE THREAD

**Issue by muhammad-ihsan** [caneco/laravel-country-logomarks#12]
**Is you request a new country in the list?**
No it's not!

**Your country community links**
- Facebook: [Laravel Indonesia](https://www.facebook.com/groups/laravel/)
- Telegram: [Laravel Indonesia](https://t.me/laravelindonesia)

**Additional context**
- National Flag: [Sang Saka Merah-Putih](https://en.wikipedia.org/wiki/Flag_of_Indonesia)
- National Emblem: [Garuda Pancasila](https://en.wikipedia.org/wiki/National_emblem_of_Indonesia)

**Comment by caneco** [comment]
Here's a preview 🇮🇩

![image](https://user-images.githubusercontent.com/502041/99004008-900a7c00-2536-11eb-9060-d65e648c7b12.png)

**Comment by caneco** [comment]
Complete in #17
