### ISSUE TITLE
Canada (CA)

### ISSUE THREAD

**Issue by brada1703** [caneco/laravel-country-logomarks#15]
Canada 🇨🇦 🇨🇦 🇨🇦

List your country community links: 

- Facebook - https://www.facebook.com/groups/laraveldeveloperscanada/
- Meetup - https://www.meetup.com/Laravel-Toronto/
- Meetup - https://www.meetup.com/Laravel-Montreal/
- Meetup - https://www.meetup.com/London-Full-Stack/ - that's London, Ontario by the way
- Meetup - https://www.meetup.com/Ottawa-PHP-Meetup/
- Meetup - https://www.meetup.com/York-Region-PHP-User-Group/
- Tinder(?) 😬 

![Meanwhile...](https://www.mtlblog.com/u/2019/01/07/14a0a4eb4effa81d35f549ac2b05e073fbb9bb0e.png_1200x630.png)

**Comment by caneco** [comment]
**Here's a preview** 🇨🇦

![image](https://user-images.githubusercontent.com/502041/99003392-ed51fd80-2535-11eb-85c3-1b0973c76b68.png)

Check #8 and discuss the option of the logomark with complexity.

**Comment by brada1703** [comment]
Very nice ❤️  I really like the one with complexity, but, yeah, I think it depends on how you do the whole set. I.e., either all or none have complexity. But, I like them both! Thanks for making this Caneco! 🤗 🤗

**Comment by caneco** [comment]
Complete in #23
