### ISSUE TITLE
Malaysia (MY)

### ISSUE THREAD

**Issue by crynobone** [caneco/laravel-country-logomarks#20]
**Is you request a new country in the list?**

No it's not!

**Your country community links**

Facebook: [Laravel Malaysia](https://www.facebook.com/groups/laravel.my)
Telegram: [Laravel Malaysia](https://t.me/laravel_malaysia)

**Additional context**

The flag colur similar to UK or US flag with addition of yellow.

National Flag: [Jalur Gemilang](https://en.wikipedia.org/wiki/Flag_of_Malaysia)
National Emblem: [Coat of Arm](https://en.wikipedia.org/wiki/Coat_of_arms_of_Malaysia)

**Comment by caneco** [comment]
**Here's a preview** 🇲🇾

![image](https://user-images.githubusercontent.com/502041/99192674-fe844f80-276b-11eb-874f-41ea5827fc88.png)

**Comment by crynobone** [comment]
Looks great, nice work @caneco

**Comment by caneco** [comment]
Complete in #24
