### ISSUE TITLE
Czech Republic (CZ)

### ISSUE THREAD

**Issue by jerryklimcik** [caneco/laravel-country-logomarks#21]
**Is you request a new country in the list?**
Yes

**Your country community links**
Pages: [Laravelblog.cz](https://laravelblog.cz/) | [Laravel.cz](https://laravel.cz/)

**Additional context**
Flag has basically same colors as France.

Here is national Flag and Greater coat of arms: [https://en.wikipedia.org/wiki/Czech_Republic](https://en.wikipedia.org/wiki/Czech_Republic)

**Comment by caneco** [comment]
**Here's a preview** 🇨🇿

![image](https://user-images.githubusercontent.com/502041/99235763-2916ec80-27ee-11eb-97df-15f7ad644c67.png)

**Comment by jerryklimcik** [comment]
Looks awesome, thank you for all work you are doing!

**Comment by caneco** [comment]
Complete in #29
