### ISSUE TITLE
Cameroon (CM)

### ISSUE THREAD

**Issue by mckenziearts** [caneco/laravel-country-logomarks#22]
**Is you request a new country in the list?**

Yes

**Your country community links**
Page: https://laravel.cm 
Twitter: https://twitter.com/laravelcm 
Facebook: https://facebook.com/laravelcm 
Slack: https://laravelcm.slack.com

**Additional context**
Here is national Flag and Greater coat of arms: https://en.wikipedia.org/wiki/Cameroon

**Comment by caneco** [comment]
**Here's a preview** 🇨🇲

![image](https://user-images.githubusercontent.com/502041/99262058-6a6ec280-2815-11eb-878b-383e11e8f8fe.png)

**Comment by mckenziearts** [comment]
Awesome that perfect

**Comment by fabriceyopa** [comment]
Amazing. I like it 🤩

**Comment by caneco** [comment]
Complete in #26
