### ISSUE TITLE
Italy (IT)

### ISSUE THREAD

**Issue by eppak** [caneco/laravel-country-logomarks#25]
**Is you request a new country in the list?**
No

**Your country community links**
http://laravel-italia.it/articoli/laravel-italia-e-su-slack
https://www.facebook.com/laravelitalia/
http://laravel-italia.it/

**Additional context**
We are the italian Laravel Community, we organize the italian Laravel Day every year.

Thanks!

**Comment by caneco** [comment]
Here's a preview 🇮🇹

![@1x](https://user-images.githubusercontent.com/502041/99455855-5794e480-2920-11eb-96ae-fe1a0fe4a8af.png)

**Comment by eppak** [comment]
Wonderful! I will use it (with your consent) for my next week talk at Laravel Day Italy, thank you a lot!

**Comment by caneco** [comment]
@eppak sure you can!! 🤩

In the following day I will add the rest of the assets… So, keep an eye in this issue 👀

-- 
Regarding the talk, It's going to be LIVE?

**Comment by eppak** [comment]
Yes, will be live but in italian [https://2020.laravelday.it/](https://2020.laravelday.it/)

**Comment by caneco** [comment]
Bravo!! We need more native speaking conferences!

```
try {
    // to have a picture of the slide during your talk :)
}
```

**Comment by eppak** [comment]
I will finish the slides in the weekend, i'll link the preview on monday if you want to take a look will use on he cover).
When have all resources ask for FB and channels update ;)
Thanks a lot for your work

**Comment by caneco** [comment]
Complete in #30

**Comment by caneco** [comment]
Complete in #30
