### ISSUE TITLE
Ghana (GH)

### ISSUE THREAD

**Issue by petersowah** [caneco/laravel-country-logomarks#28]
**Is you request a new country in the list?**
No

**Your country community links**
https://twitter.com/laravelghana

**Additional context**
We are new and just getting started. COVID slowed things down but we are working getting right back up with plans for our first conference.

**Comment by caneco** [comment]
**Here's a preview** 🇬🇭

![image](https://user-images.githubusercontent.com/502041/99674593-2f1b0080-2a6e-11eb-85f8-a7a16f6367b3.png)

**Comment by caneco** [comment]
Complete in #31

**Comment by petersowah** [comment]
Thanks @caneco . I love it!

**Comment by caneco** [comment]
@petersowah my pleasure :)
