### ISSUE TITLE
Poland (PL)

### ISSUE THREAD

**Issue by krakowiak** [caneco/laravel-country-logomarks#32]
**Is you request a new country in the list?**
Yes.

**Your country community links**
Facebook group: https://www.facebook.com/groups/laravelpolska

**Additional context**
SInce 1980 there is guideline about colors of Polish flag, and we have white which is not white at all: #E9E8E7 and red: #D4213D. The unofficial colors are #ffffff and #ff0000 respectively.

**Comment by caneco** [comment]
**Here's a preview** 🇵🇱 

![image](https://user-images.githubusercontent.com/502041/99859370-c627ab80-2b87-11eb-8c51-e4e44ae6edb0.png)

PS: I stick with the given Red, but for the White I'm using the same as the rest of the Logomarks.

**Comment by caneco** [comment]
Complete in #34
