### ISSUE TITLE
Mexico

### ISSUE THREAD

**Issue by iksaku** [caneco/laravel-country-logomarks#33]
**Is you request a new country in the list?**
First time request.

**Your country community links**
None at the moment. Tinder in progress...

**Additional context**
Our Flag is pretty similar to Italy’s one, but in case #8 is possible, we’ve got an eagle eating a snake on ours 😎.
https://commons.m.wikimedia.org/wiki/File:Flag_of_Mexico.svg

**Comment by caneco** [comment]
**Here's a preview** 🇲🇽 

![image](https://user-images.githubusercontent.com/502041/99859805-15baa700-2b89-11eb-9ac3-73cf7c76075e.png)

**Comment by caneco** [comment]
Complete in #35
