### ISSUE TITLE
Pakistan (PK)

### ISSUE THREAD

**Issue by abrardev99** [caneco/laravel-country-logomarks#6]
**Is you request a new country in the list?**
Yes, I checked the list, and PK is not there nor at requested as an issue. 

**Your country community links**
Facebook: https://web.facebook.com/groups/laravel.pakistan

**Additional context**
I would like you to see the Pakistan flag. Pakistan's flag has two colors. Green and White. 
![image](https://user-images.githubusercontent.com/54532330/98585958-d5863980-22e9-11eb-97c4-241d2f69eba9.png)

PS: The green represents the Muslim majority in Pakistan and the white stripe represents religious minorities. The flag symbolizes Pakistan's commitment to Islam and the rights of religious minorities. Want to learn more visit https://en.wikipedia.org/wiki/Flag_of_Pakistan#:~:text=The%20green%20represents%20the%20Muslim,white%20stripe%20represents%20religious%20minorities.&text=The%20flag%20symbolizes%20Pakistan's%20commitment,the%20rights%20of%20religious%20minorities.

Good Luck :)

**Comment by caneco** [comment]
@abrardev99 when I've asked for "_your country community links_," I meant if there was any Laravel community links, in this case, for Pakistan 🙂

**Comment by abrardev99** [comment]
@caneco Sorry. I updated the social links. Thank You  🙂

**Comment by caneco** [comment]
**Here's a preview**… 😊

![image](https://user-images.githubusercontent.com/502041/98714055-56901000-2380-11eb-855c-5ea035e52014.png)

**Comment by abrardev99** [comment]
I love this. Thank you @caneco

**Comment by caneco** [comment]
Complete in #19
