### ISSUE TITLE
Guatemala (GT)

### ISSUE THREAD

**Issue by ArielMejiaDev** [caneco/laravel-country-logomarks#7]
**Is you request a new country in the list?**
Yes.

**Your country community links**
facebook https://www.facebook.com/laravelgt

**Additional context**
I am starting the community for this country motivated by others that already exists.

**Comment by caneco** [comment]
**Here's the preview** 😉

![image](https://user-images.githubusercontent.com/502041/98655271-2ec88a00-2337-11eb-88dc-233f1d794b2e.png)

**@next** it's prepare all the assets

**Comment by ArielMejiaDev** [comment]
It looks amazing!!! ❤️

**Comment by caneco** [comment]
Complete in #13
