### ISSUE TITLE
Bangladesh (BD)

### ISSUE THREAD

**Issue by SumonMSelim** [caneco/laravel-country-logomarks#9]
**Is you request a new country on the list?**
- Bangladesh is not yet on the list.

**Your country community links**
Facebook Group: [Laravel Bangladesh](https://www.facebook.com/groups/LaravelBanglaDesh)

**Additional context**
National Flag: ![Bangladesh](https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg)

Bangladesh, officially the People's Republic of Bangladesh, is a country in South Asia.

**Comment by caneco** [comment]
**Here's a preview** 😁

![image](https://user-images.githubusercontent.com/502041/98738076-14c29200-239f-11eb-84e9-7ede71105819.png)

**Comment by SumonMSelim** [comment]
@caneco look cool.

**Comment by caneco** [comment]
Complete in #14
